version: "3"

services:
  app:
    build: .
    env_file:
      - .env
    depends_on:
      - postgres
    ports:
      - "3000:3000"

  postgres:
      image: postgres
      environment:
        POSTGRES_PASSWORD: qwerty
        POSTGRES_USER: qwerty
        POSTGRES_DB: advertisements
      ports:
        - 5433:5432
      volumes:
        - ./database:/var/lib/postgresql/data