version: "3"

services:
  # app:
  #   build: .
  #   depends_on:
  #     - postgres
  #   ports:
  #     - "3000:3000"
  #     - "9229:9229"

  postgres:
      image: postgres
      environment:
        POSTGRES_PASSWORD: qwerty
        POSTGRES_USER: qwerty
        POSTGRES_DB: advertisements
      ports:
        - 5433:5432
      volumes:
        - ./database:/var/lib/postgresql/data